packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': true
  esbuild: true
  webgpu: true

link-workspace-packages: true

minimumReleaseAgeExclude:
  - vitest-environment-webgpu-node@2.0.0
  - tanstack-router-ga4@1.6.0
